import Head from 'next/head'
import ShaderCanvas from 'components/ShaderApp'

export default function Home() {
    return (
        <main>
            <Head>
                <title>Next.js + R3F Shader Base</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <ShaderCanvas shaderFile="fragShader.frag" />
        </main>
    )
}
